run:
  tests: true
  timeout: 10m

linters:
  disable-all: true
  enable:
    - exportloopref
    - errcheck
    - gci
    - goconst
    - gocritic
    - gofumpt
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - staticcheck
    - thelper
    - typecheck
    - stylecheck
    - revive
    - typecheck
    - tenv
    - unconvert
    - unparam
    - unused
    - misspell