# configurations/contract_store_spam/nodes.toml

chain = "mantra"
channel = "channel-1"
denom = "uom"
prefix = "mantra"
gas_per_byte = 100
base_gas = 41772713
ibc_memo = "Contract store spam test"
memo = "Storing compiled contract with randomized memo"
ibc_memo_repeat = 10
rand_min = 15000
rand_max = 30000
revision_number = 4
timeout_height = 21720608
slip44 = 118

msg_type = "bank_send"

[msg_params]

# if this field is left blank as "", hardhat will send to random accounts endlessly
to_address = ""


#[msg_params]
wasm_file = "/Users/faddat/hardhat/target/wasm32-unknown-unknown/release/statefilestore.wasm"
label = "statefilestore"

#msg_type = "instantiate_contract"

#[msg_params]
#code_id = 1830
#label = "statefilestore"
#init_msg = '{}'
#amount = 1000

[gas]
low = 25
precision = 3

[nodes]
rpc = ["http://127.0.0.1:26657"]
api = "https://api.canary.mantrachain.dev:443"
