# configurations/v50/testiepoo.toml

chain = "umee"
channel = "channel-1"
denom = "uumee"
prefix = "umee"
gas_per_byte = 10
base_gas = 110000
ibc_memo = "Your IBC Memo"
memo = "Just checking on this"
ibc_memo_repeat = 10
rand_min = 15000
rand_max = 15000
revision_number = 4
timeout_height = 21720608
slip44 = 118

msg_type = "ibc_transfer"

[msg_params]
amount = 1000000           # Example amount
receiver = "cosmos1xyz..." # Replace with actual receiver address

[gas]
low = 1
precision = 1

[nodes]
rpc = ["http://65.109.33.48:10657"]
api = "https://umee-api.polkachu.com:443"
