chain = "luna classic"
channel = "channel-16"
denom = "uluna"
prefix = "terra"
gas_per_byte = 10
base_gas = 110000
ibc_memo = "Never again will we allow a chain to fall due to a known issue."
memo = "I bet that as predicted, size doesn't matter."
ibc_memo_repeat = 1
rand_min = 20
rand_max = 20
revision_number = 4
timeout_height = 21901107 
slip44 = 330




[gas]
low = 29325
precision = 3


[nodes]
rpc  = [
    "http://164.132.200.52:26657",
    "http://81.183.230.170:26657",
    "http://116.202.214.221:36657",
    "http://155.138.150.217:26657",
    "http://43.128.70.148:26657",
]

api = "https://terraclassic-mainnet-lcd.autostake.com:443"

# URL=`curl -L https://quicksync.io/terra.json|jq -r '.[] |select(.file=="columbus-5-pruned")|select (.mirror=="Netherlands")|.url'`
# aria2c -x5 $URL

