chain = "quasar"
channel = "channel-0"
denom = "uqsr"
prefix = "quasar"
gas_per_byte = 10
base_gas = 110000
ibc_memo = "This should not cause any problems"
memo = "Just checking on this"
ibc_memo_repeat = 10
rand_min = 400000
rand_max = 600000
revision_number = 4
timeout_height = 20720608
slip44 = 330

[gas]
zero = 0
low = 0.1
medium = 0.25
high = 0.04


[nodes]
rpc  = [
    "http://127.0.0.1:26657",
]

api = "https://quasar-api.polkachu.com:443"



