chain = "stride"
channel = "channel-0"
denom = "ustrd"
prefix = "stride"
gas_per_byte = 20
base_gas = 110000
ibc_memo = "This should not cause any problems"
memo = "Just checking on this"
ibc_memo_repeat = 10
slip44 = 118
rand_min = 20000
rand_max = 300000
revision_number = 4
timeout_height = 21720608

[gas]
low = 5
precision = 4


[nodes]
rpc  = [
    "http://83.136.251.210:26657",
]

api = "https://stride-api.polkachu.com:443"



